version: '3.8'
services:
  db:
    image: postgres:15
    container_name: shopland-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shopland
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shopland-network


  backend:
    build:
      context: ./shopland-be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - shopland-network
    depends_on:
      - db

  frontend:
    build:
      context: ./shopland-fe
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - shopland-network
    depends_on:
      - backend 


volumes:
  postgres-data:

networks:
  shopland-network:
    driver: bridge