server:
  port: 8080
  servlet:
    context-path: /shopland
spring:
  application:
    name: shopland
  datasource:
    url: jdbc:postgresql://localhost:5432/shopland
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.master.xml

logging:
  level:
    org.springframework: INFO
    agh.boksaoracz: DEBUG

security:
  jwt:
    secret-key: 2afbfac8fe49058f12874b6c7f92d6c842d2ec05f621f9b3b4ba437eb8f7b338
    expiration-time: 31536000000